=== simokbirialaoui/XML-DTD-XSL/Biblio/biblio.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT biblio (etudiant+) >
<!ELEMENT etudiant (livre+) >
<!ELEMENT livre EMPTY >
<!ATTLIST etudiant 
                       code CDATA #REQUIRED 
                       nom CDATA #REQUIRED 
                       prenom CDATA #REQUIRED 
                       age NMTOKEN #REQUIRED
                       >
<!ATTLIST livre
                       id NMTOKEN #REQUIRED
                       titre CDATA #REQUIRED
                       datEmprunt CDATA #REQUIRED
                       prix CDATA #REQUIRED
                       rendu (Oui|Non) "Non"
                       >

=== simokbirialaoui/XML-DTD-XSL/Biblio/biblio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblio SYSTEM "biblio.dtd">
<biblio>
    <etudiant code="E1" nom="Hassan" prenom="Hassan" age="23">
        <livre id="11" titre="XML" datEmprunt="2012-11-11" rendu="Oui" prix="500"/>
        <livre id="12" titre="Java" datEmprunt="2012-11-11" rendu="Non" prix="600"/>
        <livre id="12" titre="Java" datEmprunt="2012-11-11" rendu="Non" prix="100"/>
        <livre id="12" titre="Java" datEmprunt="2012-11-11" rendu="Non" prix="400"/>
    </etudiant>
    <etudiant code="E2" nom="Ilham" prenom="Ilham" age="24">
        <livre id="11" titre="XML" datEmprunt="2012-11-23" rendu="Non" prix="60"/>
        <livre id="33" titre="Oracle" datEmprunt="2012-11-23" rendu="Oui" prix="30"/>
    </etudiant>
</biblio>
